use super::error::{ChemistryError, ChemistryResult};
use super::molecule::{
    parse_java_structure, parse_legacy_structure, MolecularStructure, MolecularSummary,
};
use super::registry::ChemistryRegistryBuilder;
use super::substance::{Substance, SubstanceId, SubstanceTagId};

const DEFAULT_DENSITY_GRAMS_PER_BUCKET: f64 = 1000.0;
const DEFAULT_MOLAR_HEAT_CAPACITY: f64 = 100.0;
const DEFAULT_LATENT_HEAT: f64 = 20_000.0;
const DEFAULT_COLOR_ARGB: u32 = 0x20FF_FFFF;

pub const DESTROY_SUBSTANCE_COUNT: usize = DESTROY_SUBSTANCES.len();

#[derive(Debug, Clone, Copy)]
struct RawSubstance {
    id: &'static str,
    structure_code: Option<&'static str>,
    java_structure_code: Option<&'static str>,
    translation_key: Option<&'static str>,
    boiling_point_celsius: Option<f64>,
    boiling_point_kelvin: Option<f64>,
    density: Option<f64>,
    molar_heat_capacity: Option<f64>,
    specific_heat_capacity: Option<f64>,
    color_argb: u32,
    tags: &'static [&'static str],
}

pub fn destroy_substances_registry_builder() -> ChemistryResult<ChemistryRegistryBuilder> {
    let mut builder = ChemistryRegistryBuilder::new();
    for tag in DESTROY_TAGS {
        builder = builder.substance_tag(*tag);
    }
    for raw in DESTROY_SUBSTANCES {
        builder = builder.substance(raw.to_substance()?);
    }
    Ok(builder)
}

impl RawSubstance {
    fn to_substance(self) -> ChemistryResult<Substance> {
        let structure =
            parse_raw_structure(self.id, self.structure_code, self.java_structure_code)?;
        let summary = summarize_structure(self.id, &structure)?;
        let boiling_point_kelvin = if summary.charge != 0 {
            f64::MAX
        } else if let Some(value) = self.boiling_point_kelvin {
            value
        } else if let Some(value) = self.boiling_point_celsius {
            value + 273.0
        } else {
            estimate_boiling_point(summary.molar_mass_grams)
        };
        let molar_heat_capacity = if let Some(value) = self.molar_heat_capacity {
            value
        } else if let Some(value) = self.specific_heat_capacity {
            value / summary.molar_mass_grams
        } else {
            DEFAULT_MOLAR_HEAT_CAPACITY
        };
        let color = if self.color_argb == 0 {
            DEFAULT_COLOR_ARGB
        } else {
            self.color_argb
        };
        let tags = self
            .tags
            .iter()
            .map(|tag| SubstanceTagId::new(format!("destroy:{tag}")))
            .collect::<ChemistryResult<Vec<_>>>()?;
        Ok(Substance::new(
            SubstanceId::new(format!("destroy:{}", self.id))?,
            summary.charge,
            summary.molar_mass_grams,
            self.density.unwrap_or(DEFAULT_DENSITY_GRAMS_PER_BUCKET),
            boiling_point_kelvin,
            molar_heat_capacity,
            DEFAULT_LATENT_HEAT,
        )
        .with_catalog_metadata(
            self.structure_code
                .or(self.java_structure_code)
                .map(str::to_string),
            self.translation_key.map(str::to_string),
            color,
            tags,
        )
        .with_molecular_structure(structure))
    }
}

fn estimate_boiling_point(molar_mass_grams: f64) -> f64 {
    2.042_598_921_281_41 * molar_mass_grams + 178.176_866_128_713
}

pub fn summarize_legacy_structure(structure_code: &str) -> ChemistryResult<MolecularSummary> {
    parse_legacy_structure(structure_code)?.summary()
}

fn parse_raw_structure(
    id: &str,
    structure_code: Option<&str>,
    java_structure_code: Option<&str>,
) -> ChemistryResult<MolecularStructure> {
    match (structure_code, java_structure_code) {
        (Some(code), _) => parse_legacy_structure(code),
        (None, Some(code)) => parse_java_structure(code),
        (None, None) => Err(ChemistryError::InvalidSubstance {
            substance_id: format!("destroy:{id}"),
            reason: "substance has no structure".to_string(),
        }),
    }
}

fn summarize_structure(
    id: &str,
    structure: &MolecularStructure,
) -> ChemistryResult<MolecularSummary> {
    let summary = structure.summary()?;
    if !summary.molar_mass_grams.is_finite() || summary.molar_mass_grams <= 0.0 {
        return Err(ChemistryError::InvalidSubstance {
            substance_id: format!("destroy:{id}"),
            reason: "structure produced invalid molar mass".to_string(),
        });
    }
    Ok(summary)
}

pub const DESTROY_TAGS: &[&str] = &[
    "destroy:abundant_in_air",
    "destroy:acutely_toxic",
    "destroy:acid_rain",
    "destroy:adhesive",
    "destroy:bleach",
    "destroy:carcinogen",
    "destroy:explosive",
    "destroy:flame_retardant",
    "destroy:fragrant",
    "destroy:fuel_additive",
    "destroy:greenhouse",
    "destroy:hypothetical",
    "destroy:ozone_depleter",
    "destroy:plasticizer",
    "destroy:refrigerant",
    "destroy:smelly",
    "destroy:smog",
    "destroy:solvent",
];

const DESTROY_SUBSTANCES: &[RawSubstance] = &[
    RawSubstance {
        id: "acetamide",
        structure_code: Some(r#"destroy:linear:CC(=O)N"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(221.2),
        boiling_point_kelvin: None,
        density: Some(1159.0),
        molar_heat_capacity: Some(91.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "carcinogen", "plasticizer", "smog"],
    },
    RawSubstance {
        id: "acetate",
        structure_code: Some(r#"destroy:linear:CC~(~O^-0.5)O^-0.5"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "acetic_acid",
        structure_code: Some(r#"destroy:linear:CC(=O)OH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(118.5),
        boiling_point_kelvin: None,
        density: Some(1049.0),
        molar_heat_capacity: Some(123.1),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "acetic_anhydride",
        structure_code: Some(r#"destroy:linear:CC(=O)OC(=O)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(140.0),
        boiling_point_kelvin: None,
        density: Some(1082.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smelly", "smog"],
    },
    RawSubstance {
        id: "acetone",
        structure_code: Some(r#"destroy:linear:CC(=O)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(56.08),
        boiling_point_kelvin: None,
        density: Some(784.5),
        molar_heat_capacity: Some(126.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["solvent", "smelly", "smog"],
    },
    RawSubstance {
        id: "acetone_cyanohydrin",
        structure_code: Some(r#"destroy:linear:CC(OH)(C#N)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(95.0),
        boiling_point_kelvin: None,
        density: Some(932.0),
        molar_heat_capacity: Some(160.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog"],
    },
    RawSubstance {
        id: "acetylene",
        structure_code: Some(r#"destroy:linear:C#C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-75.0),
        boiling_point_kelvin: None,
        density: Some(613.0),
        molar_heat_capacity: Some(44.036),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "acrylonitrile",
        structure_code: Some(r#"destroy:linear:C=CC#N"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(77.0),
        boiling_point_kelvin: None,
        density: Some(810.0),
        molar_heat_capacity: Some(113.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smelly", "smog"],
    },
    RawSubstance {
        id: "adipic_acid",
        structure_code: Some(r#"destroy:linear:O=C(OH)CCCCC(=O)OH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(337.5),
        boiling_point_kelvin: None,
        density: Some(1360.0),
        molar_heat_capacity: Some(196.5),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "adiponitrile",
        structure_code: Some(r#"destroy:linear:N#CCCCCC#N"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(295.1),
        boiling_point_kelvin: None,
        density: Some(951.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog"],
    },
    RawSubstance {
        id: "aibn",
        structure_code: Some(r#"destroy:linear:CC(C)(C#N)N=NC(C)(C#N)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(10000.0),
        boiling_point_kelvin: None,
        density: Some(1100.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "ammonia",
        structure_code: Some(r#"destroy:linear:N"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-33.34),
        boiling_point_kelvin: None,
        density: Some(900.0),
        molar_heat_capacity: Some(80.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["refrigerant", "smelly"],
    },
    RawSubstance {
        id: "ammonium",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.NITROGEN, 1).addAtom(LegacyElement.HYDROGEN).addAtom(LegacyElement.HYDROGEN).addAtom(LegacyElement.HYDROGEN).addAtom(LegacyElement.HYDROGEN)"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "argon",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.ARGON)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: Some(87.302),
        density: Some(1395.4),
        molar_heat_capacity: Some(20.85),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "aspirin",
        structure_code: Some(r#"destroy:benzene:OC(=O)C,C(=O)O,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(140.0),
        boiling_point_kelvin: None,
        density: Some(1400.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "benzene",
        structure_code: Some(r#"destroy:benzene:,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(80.1),
        boiling_point_kelvin: None,
        density: Some(876.5),
        molar_heat_capacity: Some(134.8),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["carcinogen", "smog", "solvent"],
    },
    RawSubstance {
        id: "benzyl_chloride",
        structure_code: Some(r#"destroy:benzene:CCl,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(179.0),
        boiling_point_kelvin: None,
        density: Some(1100.0),
        molar_heat_capacity: Some(182.4),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "ozone_depleter", "smog"],
    },
    RawSubstance {
        id: "boric_acid",
        structure_code: Some(r#"destroy:linear:OB(O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(300.0),
        boiling_point_kelvin: None,
        density: Some(1435.0),
        molar_heat_capacity: Some(81.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "flame_retardant"],
    },
    RawSubstance {
        id: "borohydride",
        structure_code: Some(r#"destroy:linear:HB^-1(H)(H)H"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "butadiene",
        structure_code: Some(r#"destroy:linear:C=CC=C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-4.41),
        boiling_point_kelvin: None,
        density: Some(614.9),
        molar_heat_capacity: Some(123.65),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "calcium_ion",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.CALCIUM, 2)"#),
        translation_key: Some(r#"calcium"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "carbon_dioxide",
        structure_code: Some(r#"destroy:linear:O=C=O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-78.4645),
        boiling_point_kelvin: None,
        density: Some(827.3),
        molar_heat_capacity: Some(37.135),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["greenhouse"],
    },
    RawSubstance {
        id: "carbon_monoxide",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.CARBON) .addAtom(LegacyElement.OXYGEN, BondType.TRIPLE)"#,
        ),
        translation_key: None,
        boiling_point_celsius: Some(-191.5),
        boiling_point_kelvin: None,
        density: Some(789.0),
        molar_heat_capacity: Some(29.1),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "greenhouse"],
    },
    RawSubstance {
        id: "carbon_tetrachloride",
        structure_code: Some(r#"destroy:linear:ClC(Cl)(Cl)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(76.72),
        boiling_point_kelvin: None,
        density: Some(1586.7),
        molar_heat_capacity: Some(132.6),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "carcinogen", "ozone_depleter"],
    },
    RawSubstance {
        id: "chloride",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.CHLORINE, -1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "chlorine",
        structure_code: Some(r#"destroy:linear:ClCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-34.04),
        boiling_point_kelvin: None,
        density: Some(1562.5),
        molar_heat_capacity: Some(33.949),
        specific_heat_capacity: None,
        color_argb: 0x20F9FCC2,
        tags: &["acutely_toxic", "ozone_depleter", "smelly"],
    },
    RawSubstance {
        id: "chloroaurate",
        structure_code: Some(r#"destroy:linear:ClAu^-1(Cl)(Cl)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0x7FEDCA4A,
        tags: &[],
    },
    RawSubstance {
        id: "chlorodifluoromethane",
        structure_code: Some(r#"destroy:linear:ClC(F)F"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-40.7),
        boiling_point_kelvin: None,
        density: Some(1186.8),
        molar_heat_capacity: Some(112.6),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["ozone_depleter", "refrigerant"],
    },
    RawSubstance {
        id: "chloroethane",
        structure_code: Some(r#"destroy:linear:CCCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(12.27),
        boiling_point_kelvin: None,
        density: Some(889.8),
        molar_heat_capacity: Some(40.7),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["ozone_depleter", "carcinogen"],
    },
    RawSubstance {
        id: "chloroethene",
        structure_code: Some(r#"destroy:linear:C=CCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-13.4),
        boiling_point_kelvin: None,
        density: Some(911.0),
        molar_heat_capacity: Some(85.92),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["carcinogen"],
    },
    RawSubstance {
        id: "chloromethane",
        structure_code: Some(r#"destroy:linear:CCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-23.8),
        boiling_point_kelvin: None,
        density: Some(1003.0),
        molar_heat_capacity: Some(81.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "refrigerant"],
    },
    RawSubstance {
        id: "chloroform",
        structure_code: Some(r#"destroy:linear:ClC(Cl)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(61.15),
        boiling_point_kelvin: None,
        density: Some(1489.0),
        molar_heat_capacity: Some(114.25),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "ozone_depleter", "solvent"],
    },
    RawSubstance {
        id: "chromate",
        structure_code: Some(r#"destroy:linear:O=Cr=(-O^-1)(-O^-1)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xD0F7ED2C,
        tags: &[],
    },
    RawSubstance {
        id: "chromium_iii",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.CHROMIUM, 3)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xD00D9614,
        tags: &[],
    },
    RawSubstance {
        id: "cisplatin",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom( LegacyElement.PLATINUM) .addAtom(LegacyElement.CHLORINE) .addAtom(LegacyElement.CHLORINE) .addGroup( LegacyMolecularStructure.atom(LegacyElement.NITROGEN) .addAtom(LegacyElement.HYDROGEN) .addAtom(LegacyElement.HYDROGEN) .addAtom(LegacyElement.HYDROGEN), true ).addGroup( LegacyMolecularStructure.atom(LegacyElement.NITROGEN) .addAtom(LegacyElement.HYDROGEN) .addAtom(LegacyElement.HYDROGEN) .addAtom(LegacyElement.HYDROGEN), true )"#,
        ),
        translation_key: None,
        boiling_point_celsius: Some(270.0),
        boiling_point_kelvin: None,
        density: Some(3740.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "copper_i",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.COPPER, 1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xE0D30823,
        tags: &[],
    },
    RawSubstance {
        id: "copper_ii",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.COPPER, 2)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xE00FFCA1,
        tags: &[],
    },
    RawSubstance {
        id: "creatine",
        structure_code: Some(r#"destroy:linear:NC(=N)N(C)CC(=O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: Some(171.1),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "cubane",
        structure_code: Some(r#"destroy:cubane:,,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(161.6),
        boiling_point_kelvin: None,
        density: Some(1290.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "cubanedicarboxylic_acid",
        structure_code: Some(r#"destroy:cubane:C(=O)OH,,,,,,C(=O)OH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(457.4),
        boiling_point_kelvin: None,
        density: Some(2400.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "cyanamide",
        structure_code: Some(r#"destroy:linear:N#CN"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(260.0),
        boiling_point_kelvin: None,
        density: Some(1280.0),
        molar_heat_capacity: Some(78.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog", "carcinogen"],
    },
    RawSubstance {
        id: "cyanamide_ion",
        structure_code: Some(r#"destroy:linear:N^-1=C=N^-1"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "cyanide",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.CARBON, -1) .addAtom(LegacyElement.NITROGEN, BondType.TRIPLE)"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic"],
    },
    RawSubstance {
        id: "cyclohexene",
        structure_code: Some(r#"destroy:cyclohexene:,,,,,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(82.98),
        boiling_point_kelvin: None,
        density: Some(811.0),
        molar_heat_capacity: Some(152.9),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smelly", "smog"],
    },
    RawSubstance {
        id: "cyclopentadienide",
        structure_code: Some(r#"destroy:cyclopentadienide:,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "diborane",
        structure_code: Some(r#"destroy:diborane:,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-92.49),
        boiling_point_kelvin: None,
        density: Some(1131.0),
        molar_heat_capacity: Some(56.7),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "carcinogen"],
    },
    RawSubstance {
        id: "dichlorodifluoromethane",
        structure_code: Some(r#"destroy:linear:ClC(F)(F)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-28.9),
        boiling_point_kelvin: None,
        density: Some(1486.0),
        molar_heat_capacity: Some(126.8),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["greenhouse", "ozone_depleter", "refrigerant"],
    },
    RawSubstance {
        id: "dichloromethane",
        structure_code: Some(r#"destroy:linear:ClCCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(39.6),
        boiling_point_kelvin: None,
        density: Some(1326.6),
        molar_heat_capacity: Some(81.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "refrigerant", "carcinogen", "solvent"],
    },
    RawSubstance {
        id: "dichromate",
        structure_code: Some(r#"destroy:linear:O=Cr(=O)(O^-1)OCr=(=O)(O^-1)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xD0DB3D0D,
        tags: &[],
    },
    RawSubstance {
        id: "dinitrotoluene",
        structure_code: Some(r#"destroy:benzene:C,N~(~O)O,,N~(~O)O,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(250.0),
        boiling_point_kelvin: None,
        density: Some(1520.0),
        molar_heat_capacity: Some(243.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "carcinogen", "plasticizer"],
    },
    RawSubstance {
        id: "ethanol",
        structure_code: Some(r#"destroy:linear:CCO"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(78.23),
        boiling_point_kelvin: None,
        density: Some(789.45),
        molar_heat_capacity: Some(109.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["solvent", "smog"],
    },
    RawSubstance {
        id: "ethene",
        structure_code: Some(r#"destroy:linear:C=C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-103.7),
        boiling_point_kelvin: None,
        density: Some(567.9),
        molar_heat_capacity: Some(67.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "ethylanthraquinone",
        structure_code: Some(r#"destroy:anthraquinone:,,,O,,,CC,,O,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(415.4),
        boiling_point_kelvin: None,
        density: Some(1231.0),
        molar_heat_capacity: Some(286.6),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "ethylanthrahydroquinone",
        structure_code: Some(r#"destroy:anthracene:,,,O,,,CC,,O,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(415.4),
        boiling_point_kelvin: None,
        density: Some(1231.0),
        molar_heat_capacity: Some(286.6),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "ethylbenzene",
        structure_code: Some(r#"destroy:benzene:CC,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(136.0),
        boiling_point_kelvin: None,
        density: Some(866.5),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(1726.0),
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "ethoxide",
        structure_code: Some(r#"destroy:linear:CCO^-1"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "fluoride",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.FLUORINE, -1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_acid_anhydride",
        structure_code: Some(r#"destroy:linear:RC(=O)OC(=O)R"#),
        java_structure_code: None,
        translation_key: Some(r#"acid_anhydride"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_acyl_chloride",
        structure_code: Some(r#"destroy:linear:RC(=O)Cl"#),
        java_structure_code: None,
        translation_key: Some(r#"acyl_chloride"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_alcohol",
        structure_code: Some(r#"destroy:linear:RC(R)(R)O"#),
        java_structure_code: None,
        translation_key: Some(r#"alcohol"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_alkene",
        structure_code: Some(r#"destroy:linear:RC=(R)C(R)R"#),
        java_structure_code: None,
        translation_key: Some(r#"alkene"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_alkoxide",
        structure_code: Some(r#"destroy:linear:RC(R)(R)O^-1"#),
        java_structure_code: None,
        translation_key: Some(r#"alkoxide"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_alkyne",
        structure_code: Some(r#"destroy:linear:RC#CR"#),
        java_structure_code: None,
        translation_key: Some(r#"alkyne"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_amide",
        structure_code: Some(r#"destroy:linear:RC(=O)N"#),
        java_structure_code: None,
        translation_key: Some(r#"amide"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_amine",
        structure_code: Some(r#"destroy:linear:RC(R)(R)N"#),
        java_structure_code: None,
        translation_key: Some(r#"amine"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_borane",
        structure_code: Some(r#"destroy:linear:RC(R)(R)B(R)R"#),
        java_structure_code: None,
        translation_key: Some(r#"organic_borane"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_borate_ester",
        structure_code: Some(r#"destroy:linear:RC(R)(R)OB(R)R"#),
        java_structure_code: None,
        translation_key: Some(r#"borate_ester"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_carbonyl",
        structure_code: Some(r#"destroy:linear:RC=(R)O"#),
        java_structure_code: None,
        translation_key: Some(r#"carbonyl"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_carboxylic_acid",
        structure_code: Some(r#"destroy:linear:RC(=O)O"#),
        java_structure_code: None,
        translation_key: Some(r#"carboxylic_acid"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_chloride",
        structure_code: Some(r#"destroy:linear:RC(R)(R)Cl"#),
        java_structure_code: None,
        translation_key: Some(r#"organic_chloride"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_ester",
        structure_code: Some(r#"destroy:linear:RC(=O)OR"#),
        java_structure_code: None,
        translation_key: Some(r#"ester"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_isocyanate",
        structure_code: Some(r#"destroy:linear:RC(R)(R)N=C=O"#),
        java_structure_code: None,
        translation_key: Some(r#"isocyanate"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_nitrile",
        structure_code: Some(r#"destroy:linear:RC(R)(R)C#N"#),
        java_structure_code: None,
        translation_key: Some(r#"nitrile"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_nitro",
        structure_code: Some(r#"destroy:linear:RC(R)(R)N~(~O)O"#),
        java_structure_code: None,
        translation_key: Some(r#"nitro"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_organic_boric_acid",
        structure_code: Some(r#"destroy:linear:RB(R)OH"#),
        java_structure_code: None,
        translation_key: Some(r#"organic_boric_acid"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_primary_amine",
        structure_code: Some(r#"destroy:linear:RC(R)(R)N"#),
        java_structure_code: None,
        translation_key: Some(r#"non_tertiary_amine"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "generic_primary_borane",
        structure_code: Some(r#"destroy:linear:RC(R)(R)B"#),
        java_structure_code: None,
        translation_key: Some(r#"non_tertiary_borane"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "glycerol",
        structure_code: Some(r#"destroy:linear:OCC(O)CO"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(290.0),
        boiling_point_kelvin: None,
        density: Some(1261.0),
        molar_heat_capacity: Some(213.8),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "hexane_diisocyanate",
        structure_code: Some(r#"destroy:linear:O=C=NCCCCCCN=C=O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(255.0),
        boiling_point_kelvin: None,
        density: Some(1047.0),
        molar_heat_capacity: Some(222.7),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic"],
    },
    RawSubstance {
        id: "hexanediamine",
        structure_code: Some(r#"destroy:linear:NCCCCCCN"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(204.6),
        boiling_point_kelvin: None,
        density: Some(840.0),
        molar_heat_capacity: Some(250.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smelly"],
    },
    RawSubstance {
        id: "hydrazine",
        structure_code: Some(r#"destroy:linear:NN"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(114.0),
        boiling_point_kelvin: None,
        density: Some(1021.0),
        molar_heat_capacity: Some(70.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "carcinogen", "smelly", "smog"],
    },
    RawSubstance {
        id: "hydrochloric_acid",
        structure_code: Some(r#"destroy:linear:ClH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-85.05),
        boiling_point_kelvin: None,
        density: Some(1490.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(798.1),
        color_argb: 0,
        tags: &["acutely_toxic", "ozone_depleter"],
    },
    RawSubstance {
        id: "hydrofluoric_acid",
        structure_code: Some(r#"destroy:linear:FH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(19.5),
        boiling_point_kelvin: None,
        density: Some(990.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "greenhouse"],
    },
    RawSubstance {
        id: "hydrogen",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.HYDROGEN).addAtom(LegacyElement.HYDROGEN)"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: Some(20.271),
        density: Some(70.85),
        molar_heat_capacity: Some(28.84),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "hydrogen_cyanide",
        structure_code: Some(r#"destroy:linear:N#C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(26.0),
        boiling_point_kelvin: None,
        density: Some(687.6),
        molar_heat_capacity: Some(35.9),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic"],
    },
    RawSubstance {
        id: "hydrogen_iodide",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.IODINE).addAtom(LegacyElement.HYDROGEN)"#,
        ),
        translation_key: None,
        boiling_point_celsius: Some(-35.36),
        boiling_point_kelvin: None,
        density: Some(2850.0),
        molar_heat_capacity: Some(29.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "hydrogen_peroxide",
        structure_code: Some(r#"destroy:linear:OO"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(150.2),
        boiling_point_kelvin: None,
        density: Some(1110.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(2619.0),
        color_argb: 0x40C7F4FC,
        tags: &["acutely_toxic", "bleach"],
    },
    RawSubstance {
        id: "hydrogensulfate",
        structure_code: Some(r#"destroy:linear:O=S(=O)(OH)O^-1"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acid_rain"],
    },
    RawSubstance {
        id: "hydroxide",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.HYDROGEN).addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1))"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: Some(900.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "hypochlorous_acid",
        structure_code: Some(r#"destroy:linear:OCl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "bleach", "ozone_depleter", "bleach"],
    },
    RawSubstance {
        id: "hypochlorite",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.OXYGEN, -1).addAtom(LegacyElement.CHLORINE)"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "ozone_depleter"],
    },
    RawSubstance {
        id: "isoprene",
        structure_code: Some(r#"destroy:linear:C=C(C)C=C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(34.0),
        boiling_point_kelvin: None,
        density: Some(681.0),
        molar_heat_capacity: Some(102.69),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "iodide",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.IODINE, -1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "iodine",
        structure_code: Some(r#"destroy:linear:II"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(184.3),
        boiling_point_kelvin: None,
        density: Some(4933.0),
        molar_heat_capacity: Some(54.44),
        specific_heat_capacity: None,
        color_argb: 0x80AA16A5,
        tags: &[],
    },
    RawSubstance {
        id: "iodomethane",
        structure_code: Some(r#"destroy:linear:CI"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(42.6),
        boiling_point_kelvin: None,
        density: Some(2280.0),
        molar_heat_capacity: Some(82.75),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog"],
    },
    RawSubstance {
        id: "iron_ii",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.IRON, 2)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0x80A9C92A,
        tags: &[],
    },
    RawSubstance {
        id: "iron_iii",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.IRON, 3)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0x80F94939,
        tags: &[],
    },
    RawSubstance {
        id: "isopropanol",
        structure_code: Some(r#"destroy:linear:CC(O)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(82.6),
        boiling_point_kelvin: None,
        density: Some(786.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(1.54),
        color_argb: 0,
        tags: &["solvent"],
    },
    RawSubstance {
        id: "lead_ii",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.LEAD, 2)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "mercury",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.MERCURY)"#),
        translation_key: None,
        boiling_point_celsius: Some(356.73),
        boiling_point_kelvin: None,
        density: Some(13534.0),
        molar_heat_capacity: Some(27.98),
        specific_heat_capacity: None,
        color_argb: 0xFFB3B3B3,
        tags: &["acutely_toxic"],
    },
    RawSubstance {
        id: "metaxylene",
        structure_code: Some(r#"destroy:benzene:C,,C,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(139.0),
        boiling_point_kelvin: None,
        density: Some(860.0),
        molar_heat_capacity: Some(181.5),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "methane",
        structure_code: Some(r#"destroy:linear:C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-161.5),
        boiling_point_kelvin: None,
        density: Some(424.0),
        molar_heat_capacity: Some(35.7),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["greenhouse", "smog"],
    },
    RawSubstance {
        id: "methanol",
        structure_code: Some(r#"destroy:linear:CO"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(65.0),
        boiling_point_kelvin: None,
        density: Some(792.0),
        molar_heat_capacity: Some(68.62),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog", "solvent"],
    },
    RawSubstance {
        id: "methylamine",
        structure_code: Some(r#"destroy:linear:CN"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-6.3),
        boiling_point_kelvin: None,
        density: Some(656.2),
        molar_heat_capacity: Some(101.8),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "methyl_acetate",
        structure_code: Some(r#"destroy:linear:CC(=O)OC"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(56.9),
        boiling_point_kelvin: None,
        density: Some(932.0),
        molar_heat_capacity: Some(140.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog", "solvent"],
    },
    RawSubstance {
        id: "methyl_methacrylate",
        structure_code: Some(r#"destroy:linear:CC(=C)C(=O)OC"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(101.0),
        boiling_point_kelvin: None,
        density: Some(940.0),
        molar_heat_capacity: Some(191.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "methyl_salicylate",
        structure_code: Some(r#"destroy:benzene:C(=O)OC,O,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(222.0),
        boiling_point_kelvin: None,
        density: Some(1174.0),
        molar_heat_capacity: Some(248.9),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["fragrant", "smog"],
    },
    RawSubstance {
        id: "nickel_ion",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.NICKEL, 2)"#),
        translation_key: Some(r#"nickel"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0xE09BEAAB,
        tags: &["carcinogen"],
    },
    RawSubstance {
        id: "nitrate",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.NITROGEN, 1) .addAtom(LegacyElement.OXYGEN, BondType.DOUBLE) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1)) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1))"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acid_rain"],
    },
    RawSubstance {
        id: "nitric_acid",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.NITROGEN) .addAtom(LegacyElement.OXYGEN, BondType.AROMATIC) .addAtom(LegacyElement.OXYGEN, BondType.AROMATIC) .addGroup(LegacyMolecularStructure.atom(LegacyElement.OXYGEN) .addAtom(LegacyElement.HYDROGEN) ) //TODO maybe add color (though this should come from a decomposition)"#,
        ),
        translation_key: None,
        boiling_point_celsius: Some(83.0),
        boiling_point_kelvin: None,
        density: Some(1510.0),
        molar_heat_capacity: Some(53.29),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "acid_rain"],
    },
    RawSubstance {
        id: "nitrogen",
        structure_code: Some(r#"destroy:linear:N#N"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: Some(77.355),
        density: Some(807.0),
        molar_heat_capacity: Some(29.12),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["abundant_in_air"],
    },
    RawSubstance {
        id: "nitrogen_dioxide",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.NITROGEN) .addAtom(LegacyElement.OXYGEN, BondType.AROMATIC) .addAtom(LegacyElement.OXYGEN, BondType.AROMATIC)"#,
        ),
        translation_key: None,
        boiling_point_celsius: Some(21.15),
        boiling_point_kelvin: None,
        density: Some(1880.0),
        molar_heat_capacity: Some(37.2),
        specific_heat_capacity: None,
        color_argb: 0xD089011A,
        tags: &["acid_rain", "acutely_toxic", "carcinogen"],
    },
    RawSubstance {
        id: "nitroglycerine",
        structure_code: Some(r#"destroy:linear:C(ON(~O)(~O))C(ON(~O)(~O))CON(~O)(~O)"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(50.0),
        boiling_point_kelvin: None,
        density: Some(1600.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "nitronium",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.NITROGEN, 1) .addAtom(LegacyElement.OXYGEN, BondType.DOUBLE) .addAtom(LegacyElement.OXYGEN, BondType.DOUBLE)"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "octasulfur",
        structure_code: Some(r#"destroy:octasulfur:hello"#),
        java_structure_code: None,
        translation_key: Some(r#"sulfur"#),
        boiling_point_celsius: Some(444.6),
        boiling_point_kelvin: None,
        density: Some(2070.0),
        molar_heat_capacity: Some(21.64),
        specific_heat_capacity: None,
        color_argb: 0xFFD00000,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "oleum",
        structure_code: Some(r#"destroy:linear:HOS(=O)(=O)OS(=O)(=O)OH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(10.0),
        boiling_point_kelvin: None,
        density: Some(1820.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(2600.0),
        color_argb: 0,
        tags: &["acid_rain", "acutely_toxic"],
    },
    RawSubstance {
        id: "orthoxylene",
        structure_code: Some(r#"destroy:benzene:C,C,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(144.4),
        boiling_point_kelvin: None,
        density: Some(880.0),
        molar_heat_capacity: Some(187.1),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "oxide",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.OXYGEN, -2)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "oxygen",
        structure_code: Some(r#"destroy:linear:O=O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: Some(90.188),
        density: Some(1141.0),
        molar_heat_capacity: Some(29.378),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["abundant_in_air"],
    },
    RawSubstance {
        id: "paraxylene",
        structure_code: Some(r#"destroy:benzene:C,,,C,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(138.35),
        boiling_point_kelvin: None,
        density: Some(861.0),
        molar_heat_capacity: Some(182.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "phenol",
        structure_code: Some(r#"destroy:benzene:O,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(181.7),
        boiling_point_kelvin: None,
        density: Some(1070.0),
        molar_heat_capacity: Some(220.9),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smelly", "smog"],
    },
    RawSubstance {
        id: "phenylacetic_acid",
        structure_code: Some(r#"destroy:benzene:CC(=O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(265.5),
        boiling_point_kelvin: None,
        density: Some(1080.9),
        molar_heat_capacity: Some(170.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["fragrant", "smog"],
    },
    RawSubstance {
        id: "phenylacetone",
        structure_code: Some(r#"destroy:benzene:CC(=O)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(215.0),
        boiling_point_kelvin: None,
        density: Some(1006.0),
        molar_heat_capacity: Some(250.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "smog"],
    },
    RawSubstance {
        id: "phosgene",
        structure_code: Some(r#"destroy:linear:ClC(=O)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(8.3),
        boiling_point_kelvin: None,
        density: Some(1432.0),
        molar_heat_capacity: Some(101.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "ozone_depleter", "smelly"],
    },
    RawSubstance {
        id: "phthalic_anhydride",
        structure_code: Some(r#"destroy:isohydrobenzofuran:,,,O,O,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(295.0),
        boiling_point_kelvin: None,
        density: Some(1530.0),
        molar_heat_capacity: Some(161.8),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "picric_acid",
        structure_code: Some(r#"destroy:benzene:O,N~(~O)O,,N~(~O)O,,N~(~O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(300.0),
        boiling_point_kelvin: None,
        density: Some(1763.0),
        molar_heat_capacity: Some(200.0),
        specific_heat_capacity: None,
        color_argb: 0xC0ED7417,
        tags: &["smog"],
    },
    RawSubstance {
        id: "potassium_ion",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.POTASSIUM, 1)"#),
        translation_key: Some(r#"potassium"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "propene",
        structure_code: Some(r#"destroy:linear:C=CC"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-47.6),
        boiling_point_kelvin: None,
        density: Some(1810.0),
        molar_heat_capacity: Some(102.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "salicylic_acid",
        structure_code: Some(r#"destroy:benzene:C(=O)O,O,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(200.0),
        boiling_point_kelvin: None,
        density: Some(1443.0),
        molar_heat_capacity: Some(159.4),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "sodium_metal",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.SODIUM)"#),
        translation_key: Some(r#"sodium"#),
        boiling_point_celsius: Some(882.94),
        boiling_point_kelvin: None,
        density: Some(968.0),
        molar_heat_capacity: Some(28.23),
        specific_heat_capacity: None,
        color_argb: 0xFFB3B3B3,
        tags: &[],
    },
    RawSubstance {
        id: "sodium_ion",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.SODIUM, 1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: Some(900.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "styrene",
        structure_code: Some(r#"destroy:benzene:C=C,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(145.0),
        boiling_point_kelvin: None,
        density: Some(909.0),
        molar_heat_capacity: Some(183.2),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smog"],
    },
    RawSubstance {
        id: "sulfate",
        structure_code: None,
        java_structure_code: Some(
            r#"LegacyMolecularStructure.atom(LegacyElement.SULFUR, 2) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1)) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1)) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1)) .addAtom(new LegacyAtom(LegacyElement.OXYGEN, -1))"#,
        ),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acid_rain"],
    },
    RawSubstance {
        id: "sulfide",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.SULFUR, -2)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "sulfur_dioxide",
        structure_code: Some(r#"destroy:linear:O=S=O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-10.0),
        boiling_point_kelvin: None,
        density: Some(2628.8),
        molar_heat_capacity: Some(39.87),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "acid_rain"],
    },
    RawSubstance {
        id: "sulfuric_acid",
        structure_code: Some(r#"destroy:linear:OS(=O)(=O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(337.0),
        boiling_point_kelvin: None,
        density: Some(1830.2),
        molar_heat_capacity: Some(83.68),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "acid_rain"],
    },
    RawSubstance {
        id: "sulfur_trioxide",
        structure_code: Some(r#"destroy:linear:S=(=O)(=O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(45.0),
        boiling_point_kelvin: None,
        density: Some(1920.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(50.6),
        color_argb: 0,
        tags: &["acutely_toxic", "acid_rain"],
    },
    RawSubstance {
        id: "tetraethyllead",
        structure_code: Some(r#"destroy:linear:CCPb(CC)(CC)CC"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(84.5),
        boiling_point_kelvin: None,
        density: Some(1653.0),
        molar_heat_capacity: Some(307.4),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["fuel_additive", "smog", "carcinogen", "acutely_toxic"],
    },
    RawSubstance {
        id: "tetrafluoroethene",
        structure_code: Some(r#"destroy:linear:FC=(F)C(F)F"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(-76.3),
        boiling_point_kelvin: None,
        density: Some(1519.0),
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["acutely_toxic", "greenhouse", "smog"],
    },
    RawSubstance {
        id: "tetrahydroxyborate",
        structure_code: Some(r#"destroy:linear:OB^-1(O)(O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "tetrahydroxy_tetraborate",
        structure_code: Some(r#"destroy:tetraborate:O,O,O,O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "thionyl_chloride",
        structure_code: Some(r#"destroy:linear:S=(=O)(Cl)(Cl)"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(74.6),
        boiling_point_kelvin: None,
        density: Some(1638.0),
        molar_heat_capacity: Some(121.0),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "acutely_toxic"],
    },
    RawSubstance {
        id: "toluene",
        structure_code: Some(r#"destroy:benzene:C,,,,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(110.6),
        boiling_point_kelvin: None,
        density: Some(862.3),
        molar_heat_capacity: Some(157.3),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["carcinogen", "smog", "solvent"],
    },
    RawSubstance {
        id: "toluene_diisocyanate",
        structure_code: Some(r#"destroy:benzene:C,N=C=O,,N=C=O,,"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(251.0),
        boiling_point_kelvin: None,
        density: Some(1214.0),
        molar_heat_capacity: Some(222.7),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["carcinogen", "acutely_toxic"],
    },
    RawSubstance {
        id: "trichlorofluoromethane",
        structure_code: Some(r#"destroy:linear:FC(Cl)(Cl)Cl"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(23.77),
        boiling_point_kelvin: None,
        density: Some(1494.0),
        molar_heat_capacity: Some(122.5),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["greenhouse", "ozone_depleter", "refrigerant", "smog"],
    },
    RawSubstance {
        id: "trimethylamine",
        structure_code: Some(r#"destroy:linear:CN(C)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(5.0),
        boiling_point_kelvin: None,
        density: Some(670.0),
        molar_heat_capacity: Some(132.55),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["smelly", "smog"],
    },
    RawSubstance {
        id: "trimethyl_borate",
        structure_code: Some(r#"destroy:linear:COB(OC)OC"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(68.5),
        boiling_point_kelvin: None,
        density: Some(932.0),
        molar_heat_capacity: Some(189.9),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "tnt",
        structure_code: Some(r#"destroy:benzene:C,N~(~O)O,,N~(~O)O,,N~(~O)O"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(240.0),
        boiling_point_kelvin: None,
        density: Some(1654.0),
        molar_heat_capacity: Some(243.3),
        specific_heat_capacity: None,
        color_argb: 0xD0FCF1E8,
        tags: &["acutely_toxic", "carcinogen", "smog"],
    },
    RawSubstance {
        id: "vinyl_acetate",
        structure_code: Some(r#"destroy:linear:C=COC(=O)C"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(72.7),
        boiling_point_kelvin: None,
        density: Some(934.0),
        molar_heat_capacity: Some(169.5),
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &["adhesive", "carcinogen", "fragrant", "smog"],
    },
    RawSubstance {
        id: "water",
        structure_code: Some(r#"destroy:linear:HOH"#),
        java_structure_code: None,
        translation_key: None,
        boiling_point_celsius: Some(100.0),
        boiling_point_kelvin: None,
        density: Some(1000.0),
        molar_heat_capacity: None,
        specific_heat_capacity: Some(4160.0),
        color_argb: 0,
        tags: &["greenhouse", "solvent"],
    },
    RawSubstance {
        id: "zinc_ion",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.ZINC, 2)"#),
        translation_key: Some(r#"zinc"#),
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
    RawSubstance {
        id: "proton",
        structure_code: None,
        java_structure_code: Some(r#"LegacyMolecularStructure.atom(LegacyElement.HYDROGEN, 1)"#),
        translation_key: None,
        boiling_point_celsius: None,
        boiling_point_kelvin: None,
        density: None,
        molar_heat_capacity: None,
        specific_heat_capacity: None,
        color_argb: 0,
        tags: &[],
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn destroy_catalog_builds_all_explicit_substances() {
        let registry = destroy_substances_registry_builder()
            .unwrap()
            .build()
            .unwrap();

        assert_eq!(DESTROY_SUBSTANCE_COUNT, 152);
        assert_eq!(registry.substance_count(), 152);
    }

    #[test]
    fn key_destroy_substances_match_legacy_properties() {
        let registry = destroy_substances_registry_builder()
            .unwrap()
            .build()
            .unwrap();

        let water = registry.substance(&"destroy:water".into()).unwrap();
        assert_eq!(water.charge, 0);
        assert!((water.molar_mass_grams - 18.02).abs() < 0.001);
        assert!((water.boiling_point_kelvin - 373.0).abs() < 0.001);
        assert!((water.molar_heat_capacity_j_per_mol_kelvin - (4160.0 / 18.02)).abs() < 0.001);

        let proton = registry.substance(&"destroy:proton".into()).unwrap();
        assert_eq!(proton.charge, 1);
        assert!((proton.molar_mass_grams - 1.01).abs() < 0.001);
        assert_eq!(proton.boiling_point_kelvin, f64::MAX);

        let hydroxide = registry.substance(&"destroy:hydroxide".into()).unwrap();
        assert_eq!(hydroxide.charge, -1);
        assert!((hydroxide.molar_mass_grams - 17.01).abs() < 0.001);
        assert_eq!(hydroxide.boiling_point_kelvin, f64::MAX);

        let ammonium = registry.substance(&"destroy:ammonium".into()).unwrap();
        assert_eq!(ammonium.charge, 1);
        assert!((ammonium.molar_mass_grams - 18.05).abs() < 0.001);

        let acetate = registry.substance(&"destroy:acetate".into()).unwrap();
        assert_eq!(acetate.charge, -1);
        assert!((acetate.molar_mass_grams - 59.04).abs() < 0.01);

        let chloride = registry.substance(&"destroy:chloride".into()).unwrap();
        assert_eq!(chloride.charge, -1);
        assert!((chloride.molar_mass_grams - 35.45).abs() < 0.001);

        let argon = registry.substance(&"destroy:argon".into()).unwrap();
        assert_eq!(argon.charge, 0);
        assert!((argon.molar_mass_grams - 39.95).abs() < 0.001);
        assert!((argon.boiling_point_kelvin - 87.302).abs() < 0.001);
    }

    #[test]
    fn legacy_structure_rejects_unknown_element_and_bad_charge() {
        assert!(summarize_legacy_structure("destroy:linear:Xx").is_err());
        assert!(summarize_legacy_structure("destroy:linear:O^-nope").is_err());
    }
}
